version: "3.7"
services:
  composerinstall:
    image: chadubab/sample-project
    container_name: sample-project-composer-install
    working_dir: /var/www/html/
    command: composer install
    volumes:
      - ./:/var/www/html/
    networks:
      - sample-project-docker-network

  keygen:
    image: chadubab/sample-project
    container_name: sample-project-keygen
    working_dir: /var/www/html/
    command: php artisan key:generate
    volumes:
      - ./:/var/www/html/
    depends_on:
      - composerinstall
    networks:
      - sample-project-docker-network

  appservice:
    image: chadubab/sample-project
    container_name: sample-project
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    ports:
      - 8020:8000
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      CACHE_DRIVER: ${CACHE_DRIVER}
      FILESYSTEM_DRIVER: ${FILESYSTEM_DRIVER}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_LIFETIME: ${SESSION_LIFETIME}
    depends_on:
      - database
    links:
      - database
    networks:
      - sample-project-docker-network

  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: database
    expose:
      - 3306
    depends_on:
      - composerinstall
    networks:
      - sample-project-docker-network

networks:
  sample-project-docker-network:
    driver: bridge